---
- name: P1 - Installs necessary project dependencies on workers
  hosts: workers
  roles:
    - workers
  tasks:
    - name: T1 - Clone registry repository
      ansible.builtin.git:
        repo: '{{ workers_mvn_repo }}'
        dest: '{{ workers_project_dir }}'
        single_branch: yes
        version: releases
        force: yes

- name: P2 - Installs necessary project dependencies on nodes
  hosts: nodes
  roles:
    - nodes
  tasks:
    - name: T1 - Create lib directory in nodes working dir
      file:
        path: '{{ nodes_working_dir }}/lib'
        state: directory

    - name: T2 - Get slf4j-reload4j dependency for nodes
      get_url:
        url: 'https://repo1.maven.org/maven2/org/slf4j/slf4j-reload4j/{{ all_GROUP_slf4j_reload4j_version }}/slf4j-reload4j-{{ all_GROUP_slf4j_reload4j_version }}.jar'
        dest: '{{ nodes_working_dir }}/lib/slf4j-reload4j.jar'
        force: yes

    - name: T3 - Get reload4j dependency for nodes
      get_url:
        url: "https://repo1.maven.org/maven2/ch/qos/reload4j/reload4j/{{ all_GROUP_reload4j_version }}/reload4j-{{ all_GROUP_reload4j_version }}.jar"
        dest: '{{ nodes_working_dir }}/lib/reload4j.jar'
        force: yes

    - name: T4 - Rename consensus.jar
      shell: "mv *.jar consensus.jar"
      args:
        chdir: "{{ nodes_working_dir }}"

- name: P3 - Installs necessary project dependencies on clients
  hosts: clients
  roles:
    - clients
  tasks:
    - name: T1 - Untar ycsb tar file
      shell: "tar xvf *.tar.gz --strip 1 -C ."
      args:
        chdir: "{{ clients_working_dir }}"

    - name: T2 - Get slf4j-reload4j dependency for clients
      get_url:
        url: 'https://repo1.maven.org/maven2/org/slf4j/slf4j-reload4j/{{ all_GROUP_slf4j_reload4j_version }}/slf4j-reload4j-{{ all_GROUP_slf4j_reload4j_version }}.jar'
        dest: '{{ clients_working_dir }}/lib/slf4j-reload4j.jar'
        force: yes

    - name: T3 - Get reload4j dependency for clients
      get_url:
        url: "https://repo1.maven.org/maven2/ch/qos/reload4j/reload4j/{{ all_GROUP_reload4j_version }}/reload4j-{{ all_GROUP_reload4j_version }}.jar"
        dest: '{{ clients_working_dir }}/lib/reload4j.jar'
        force: yes

- name: P4 - Configure log4j on workers
  hosts: workers
  roles:
    - workers
  tasks:
    - name: T1 - Create logs directory
      file:
        path: '{{ workers_project_log_path }}'
        state: directory

    - name: T2 - Copy log4j template
      template:
        src: log4j.template.j2
        dest: '{{ workers_project_log_path }}/log4j.properties'
