#------------------------------------------------------------------------------------------------------------
# A playbook that installs necessary software dependencies and configures required environment variables
# on all nodes.
#------------------------------------------------------------------------------------------------------------

---
- name: P1 - Sets Up the VMs
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: P1.1 - Changing hostname of the machine
      shell:
        cmd: |
          bash -ilc 'sudo hostnamectl set-hostname {{ inventory_hostname }}'

    - name: P1.2 - Sending private key file to instances
      copy:
          src: "{{ all_GROUP_instance_private_key_file }}"
          dest: "{{ all_GROUP_home_dir }}/.ssh/id_rsa"
          mode: "0600"

    - name: P1.3 - Copy the remote data scripts
      copy:
        src: ./remote_data_scripts/
        dest: "{{ all_GROUP_home_dir }}"
        mode: "0777"

    - name: P1.4 - Copy the remote bash scripts
      copy:
        src: ./remote_bash_scripts/
        dest: "{{ all_GROUP_home_dir }}"
        mode: "0777"

    - name: P1.5 - Run the setup_vm script (async)
      shell:
        cmd: |
          bash -ilc './setup_vm.sh'
        chdir: "{{ all_GROUP_home_dir }}"
      async: 600
      poll: 0
      register: setup_vm_task

    - name: Waiting all to finish VM setup
      async_status:
        jid: "{{ setup_vm_task.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 10
      delay: 60