#------------------------------------------------------------------------------------------------------------
# A playbook that installs necessary project dependencies on collectors.
# NB! This playbook is not idempotent as it will overwrite the project directory.
#------------------------------------------------------------------------------------------------------------

---
- name: P3.1 - Installs necessary project dependencies on collectors
  hosts: collectors
  any_errors_fatal: true
  tasks:
    - name: Starting Graphite docker container
      shell:
        cmd: |
          # run detached
          bash -ilc 'docker run -d \
                      --name graphite \
                      -p {{ collectors_GROUP_graphite_web_port }}:80 \
                      -p {{ collectors_GROUP_graphite_nc_port }}:2003 \
                      -p 2023-2024:2023-2024 \
                      -p 8125:8125/udp \
                      -p 8126:8126 \
                      graphiteapp/graphite-statsd'
