#------------------------------------------------------------------------------------------------------------
# Performs a simple load test using raft consensus protocol with a custom workload definition.
#------------------------------------------------------------------------------------------------------------

---
- ansible.builtin.import_playbook: util_start_load_test.yaml
  vars:
    test_name: "S1"
    consensus_protocol: "raft"
    node_cli_params: >-
      metrics.jvm.enabled=true
      metrics.insights.enabled=true
    store_cli_params: >-
      metrics.jvm.enabled=true
      metrics.insights.enabled=true
    workload: |
      recordcount=1000
      operationcount=1000
      workload=site.ycsb.workloads.CoreWorkload
      
      readallfields=true
      
      readproportion=0.5
      updateproportion=0.5
      scanproportion=0
      insertproportion=0
      
      requestdistribution=zipfian
