#------------------------------------------------------------------------------------------------------------
# Performs a simple load test using bizur consensus protocol with a custom workload definition.
#------------------------------------------------------------------------------------------------------------

---
- import_playbook: T_load_test_consensus_bizur.yaml
  vars:
    test_group: "S"
    test_name: "S2"
    workload_definition: |
      recordcount=1000
      operationcount=1000
      workload=site.ycsb.workloads.CoreWorkload
      
      readallfields=true
      
      readproportion=0.5
      updateproportion=0.5
      scanproportion=0
      insertproportion=0
      
      requestdistribution=zipfian
    performance_analysis: true
    resource_usage_analysis: true
    message_analysis: true
    bizur_num_buckets: 1000