#------------------------------------------------------------------------------------------------------------
# Performs a simple load test with failure injection (using raft consensus).
#------------------------------------------------------------------------------------------------------------

---
- import_playbook: T_load_test_consensus_raft.yaml
  vars:
    test_group: "S"
    test_name: "S3"
    workload_definition: |
      recordcount=1000
      operationcount=1000
      workload=site.ycsb.workloads.CoreWorkload
      
      readallfields=true
      
      readproportion=0.5
      updateproportion=0.5
      scanproportion=0
      insertproportion=0
      
      requestdistribution=zipfian
    performance_analysis: true
    resource_usage_analysis: true
    message_analysis: true

    inject_fault:
      condition: 'disconnect follower'
      delay_sec: 10
      duration_sec: 60