#------------------------------------------------------------------------------------------------------------
# Performs a simple load test with failure injection.
#------------------------------------------------------------------------------------------------------------

---
- ansible.builtin.import_playbook: util_start_load_test.yaml
  vars:
    test_name: "S3"
    consensus_protocol: "raft"
    node_cli_params: ""
    store_cli_params: ""
    workload: |
      recordcount=1000
      operationcount=1000
      workload=site.ycsb.workloads.CoreWorkload

      readallfields=true

      readproportion=0.5
      updateproportion=0.5
      scanproportion=0
      insertproportion=0

      requestdistribution=zipfian

    inject_fault:
      condition: 'disconnect follower'
      delay_sec: 10
      duration_sec: 60