#------------------------------------------------------------------------------------------------------------
# Performs a simple load test on etcd cluster with a custom workload definition.
#------------------------------------------------------------------------------------------------------------

---
- import_playbook: T_load_test_etcd_raft.yaml
  vars:
    test_group: "S"
    test_name: "S5"
    workload_definition: |
      recordcount=1000
      operationcount=1000
      workload=site.ycsb.workloads.CoreWorkload
      
      readallfields=true
      
      readproportion=0.5
      updateproportion=0.5
      scanproportion=0
      insertproportion=0
      
      requestdistribution=zipfian
    performance_analysis: true
    resource_usage_analysis: false
    message_analysis: false