
---
- import_playbook: util_start_load_test.yaml
  vars:
    test_name: "T1"
    consensus_protocol: "simulate"
    node_cli_params: >-
      simulate.leaderId={{ lookup('env','NODE_ID_TO_USE_AS_STORE') | mandatory }}
      simulate.leader.broadcastToFollowers=false
      simulate.follower.forwardToLeader=false
    store_cli_params: >-
      simulate.leaderId={{ lookup('env','NODE_ID_TO_USE_AS_STORE') | mandatory }}
      simulate.leader.broadcastToFollowers=false
      simulate.follower.forwardToLeader=false
    resource_usage_analysis: false
    message_analysis: false
    workload: "{{ workload_file | default('workload_read_write_proportional') | string }}"