#------------------------------------------------------------------------------------------------------------
# Performs a load test of the etcd cluster with an optionally provided workload definition.
#------------------------------------------------------------------------------------------------------------

---
- import_playbook: util_etcd_start_load_test.yaml
  vars:
    test_name: "T4"
    workload: "{{ workload_file | default('workload_read_write_proportional') | string }}"
