#------------------------------------------------------------------------------------------------------------
# Performs a simple load test using raft consensus protocol with a custom workload definition.
#------------------------------------------------------------------------------------------------------------

---
- import_playbook: util_start_load_test.yaml
  vars:
    consensus_protocol: "raft"
    node_cli_params: >-
      --node
      metrics.jvm.enabled={{ analyze_store_jvm_metrics }}
      metrics.insights.enabled={{ analyze_store_message_metrics }}
    workload: "{{ workload_definition }}"
