#------------------------------------------------------------------------------------------------------------
# Performs a load test of the consul cluster with the provided workload definition.
#------------------------------------------------------------------------------------------------------------

---
- import_playbook: util_start_load_test_etcd_consul.yaml
  vars:
    consensus_protocol: "consul_raft"
    cluster_type: "consul"
    workload: "{{ workload_definition }}"
