#------------------------------------------------------------------------------------------------------------
# Performs a load test of the etcd cluster with the provided workload definition.
#------------------------------------------------------------------------------------------------------------

---
- import_playbook: util_start_load_test_etcd_consul.yaml
  vars:
    consensus_protocol: "etcd_raft"
    cluster_type: "etcd"
    workload: "{{ workload_definition }}"
