#------------------------------------------------------------------------------------------------------------
# Performs a load test of the consul cluster with the provided workload definition.
#------------------------------------------------------------------------------------------------------------

---
- import_playbook: util_start_load_test.yaml
  vars:
    cluster_type: "consul"
    consensus_protocol: "raft"
    workload: "{{ workload_definition }}"
    analyze_store_jvm_metrics: false
    analyze_store_message_metrics: false