#------------------------------------------------------------------------------------------------------------
# Performs a load test of the consul cluster with the provided workload definition.
#------------------------------------------------------------------------------------------------------------

---
- import_playbook: util_start_load_test_consul.yaml
  vars:
    workload: "{{ workload_definition }}"
