#------------------------------------------------------------------------------------------------------------
# Starts workers
#------------------------------------------------------------------------------------------------------------

---
- import_playbook: util_start_consensus_workers.yaml
  when: cluster_type == "consensus"

- import_playbook: util_start_etcd_workers.yaml
  when: cluster_type == "etcd"

- import_playbook: util_start_consul_workers.yaml
  when: cluster_type == "consul"
