#------------------------------------------------------------------------------------------------------------
# Cleanup resources
#------------------------------------------------------------------------------------------------------------

---
- ansible.builtin.import_playbook: util_stop_workers.yaml

- name: Cleans up workers
  hosts: workers

  tasks:
    - name: Deleting worker logs
      shell:
        cmd: |
          set -m
          # clean up log files (errors ignored)
          bash -ilc 'rm {{ workers_GROUP_project_log_file }} || true'
      when: delete_logs | default('true') | bool

    - name: Deleting worker metrics
      shell:
        cmd: |
          set -m
          # clean up metrics files (errors ignored)
          bash -ilc 'rm {{ workers_GROUP_project_metrics_file }} || true'
      when: delete_metrics | default('true') | bool