#------------------------------------------------------------------------------------------------------------
# Collects metrics generated at workers to local controller and groups them into csv files
#------------------------------------------------------------------------------------------------------------

---

- name: Fetches logs from workers to local controller (if DEBUG)
  hosts: workers
  any_errors_fatal: true
  tasks:
    - name: Fetching worker logs
      fetch:
        src: "{{ workers_GROUP_project_log_file }}"
        dest: "{{ lookup('env','METRICS_BASE_PATH') | mandatory }}/{{ test_name }}/{{ _server_name }}.logs.log"
        flat: yes
      vars:
        _server_name: "{{ group_names[0] }}"
      when: workers_GROUP_project_log_level is search("DEBUG")

- name: Collects metrics from clients into csv files
  hosts: clients
  any_errors_fatal: true
  tasks:
    - name: Fetching client metrics
      fetch:
        src: "{{ workers_GROUP_project_metrics_file }}"
        dest: "{{ lookup('env','METRICS_BASE_PATH') | mandatory }}/{{ test_name }}/{{ _server_name }}.metrics.txt"
        flat: yes
      vars:
        _server_name: "{{ group_names[0] }}"

    - name: Grouping client (perf test) metrics (using R on controller)
      delegate_to: 127.0.0.1
      shell:
        cmd: |
          ./collect_client_metrics.R {{ _metrics_file }} {{ _output_folder }} {{ test_name }} {{ consensus_protocol }}
        chdir: "{{ _working_dir }}"
      vars:
        _working_dir: "{{ lookup('env','LOCAL_SCRIPTS_PATH') | mandatory }}"
        _metrics_path: "{{ lookup('env','METRICS_BASE_PATH') | mandatory }}/{{ test_name }}"
        _server_name: "{{ clients_GROUP_current_client_name }}"
        _metrics_file: "{{ _metrics_path }}/{{ _server_name }}.metrics.txt"
        _output_folder: "{{ _metrics_path }}"

- name: Collects metrics from stores into csv files
  hosts: stores
  any_errors_fatal: true
  tasks:
    - name: Fetching store metrics
      fetch:
        src: "{{ workers_GROUP_project_metrics_file }}"
        dest: "{{ lookup('env','METRICS_BASE_PATH') | mandatory }}/{{ test_name }}/{{ _server_name }}.metrics.txt"
        flat: yes
      vars:
        _server_name: "{{ group_names[0] }}"
      when:
        "nodes_GROUP_jvm_metrics_enabled is true"

    - name: Grouping store metrics (using R on controller)
      delegate_to: 127.0.0.1
      shell:
        cmd: |
          ./collect_store_metrics.R {{ _metrics_file }} {{ _output_folder }} {{ test_name }} {{ consensus_protocol }}
        chdir: "{{ _working_dir }}"
      vars:
        _working_dir: "{{ lookup('env','LOCAL_SCRIPTS_PATH') | mandatory }}"
        _metrics_path: "{{ lookup('env','METRICS_BASE_PATH') | mandatory }}/{{ test_name }}"
        _server_name: "{{ nodes_GROUP_current_node_name }}"
        _metrics_file: "{{ _metrics_path }}/{{ _server_name }}.metrics.txt"
        _output_folder: "{{ _metrics_path }}"
      when:
        "nodes_GROUP_jvm_metrics_enabled is true"