#------------------------------------------------------------------------------------------------------------
# Collects logs generated at workers to local controller
#------------------------------------------------------------------------------------------------------------

---

- name: Fetches logs from workers to local controller
  hosts: workers
  any_errors_fatal: true
  tasks:
    - name: Fetching worker logs
      fetch:
        src: "{{ workers_GROUP_project_log_file }}"
        dest: "{{ _base_path }}/{{ _file_name }}"
        flat: yes
      vars:
        _base_path: "{{ lookup('env','COLLECTED_LOGS_PATH') | mandatory }}"
        _file_name: "{{ test_group }}{{ test_name }}_{{ inventory_hostname }}.log"
      when: workers_GROUP_project_log_level is search("DEBUG")
