#------------------------------------------------------------------------------------------------------------
# Playbook that starts an etcd cluster and performs load tests on it with the provided params.
# It then collects client (YCSB) metrics, analyzes them and cleans up the workers.
#------------------------------------------------------------------------------------------------------------

---
# ------------------------------------------------------------------------------------ Runtime configuration
- ansible.builtin.import_playbook: util_runtime_config.yaml

# ------------------------------------------------------------------------------------ Load test
- name: Starts all etcd KV stores
  hosts: nodes
  tasks:
    - name: Starting all etcd KV stores (async)
      shell:
        cmd: |
          set -m
          
          # run in background
          bash -ilc '
            etcdMyPeerIp=$(~/private_ip.sh); echo $etcdMyPeerIp;
            ./etcd  --name "node{{ nodes_GROUP_current_node_id }}" \
                    --initial-advertise-peer-urls "http://$etcdMyPeerIp:{{ nodes_GROUP_node_serving_port }}" \
                    --listen-peer-urls "http://$etcdMyPeerIp:{{ nodes_GROUP_node_serving_port }}" \
                    --listen-client-urls "http://$etcdMyPeerIp:{{ nodes_GROUP_client_serving_port }}" \
                    --advertise-client-urls "http://$etcdMyPeerIp:{{ nodes_GROUP_client_serving_port }}" \
                    --initial-cluster-token my-etcd-cluster-1 \
                    --initial-cluster "{{ workers_GROUP_etcd_node_destinations }}" \
                    --data-dir {{ nodes_GROUP_etcd_working_dir }}/data \
                    --initial-cluster-state new &> {{ workers_GROUP_project_log_file }}' &
          
          bash -ilc 'sleep 1m'
        chdir: "{{ nodes_GROUP_etcd_working_dir }}"
      async: 100
      poll: 0
      register: start_stores_task

    - name: Waiting stores to start
      async_status:
        jid: "{{ start_stores_task.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 10

- name: Starts client(s)
  hosts: clients
  tasks:
    - name: Starting client(s) (perf test)
      shell:
        cmd: |
          set -m
          
          workload="{{ workload }}"
          workloadFile="{{ clients_GROUP_workloads_dir }}/{{ workload }}"
          if [ ! -f "$workloadFile" ]; then
            echo "received custom workload:"
            echo "$workload"
            echo "$workload" > "{{ clients_GROUP_workloads_dir }}/workload_file"
          else
            cp "$workloadFile" "{{ clients_GROUP_workloads_dir }}/workload_file"
          fi
          
          bash -ilc 'export JAVA_OPTS="-Dlog4j.configuration=file:{{ workers_GROUP_project_log_config_file}}" && \
                      ./bin/ycsb.sh run etcd {{ _metrics_params }} {{ _client_params }} -P {{ clients_GROUP_workloads_dir }}/workload_file'
        chdir: "{{ clients_GROUP_working_dir }}"
      vars:
        _metrics_params: >-
          -p measurementtype=raw
          -p measurement.raw.output_file={{ workers_GROUP_project_metrics_file }}
          -p measurement.raw.graphite=true
          -p measurement.raw.separator=,
          -p exportfile={{ workers_GROUP_project_metrics_file }}
        _client_params: >-
          -p cluster.members={{ workers_GROUP_etcd_store_destinations }}

- name: Stops workers
  hosts: workers
  tasks:
    - name: Stopping worker processes
      shell:
        cmd: |
          set -m
          
          # kill etcd processes (errors ignored)
          bash -ilc 'kill $(ps -A | grep etcd | awk "{print $1}") || true'

          # kill any java processes (errors ignored)
          bash -ilc 'kill $(ps -A | grep java | awk "{print $1}") || true'

# ------------------------------------------------------------------------------------ Metric collection & analysis

- name: Fetches metrics from clients to local controller
  hosts: clients
  any_errors_fatal: true
  tasks:
    - name: Fetching metrics
      fetch:
        src: "{{ workers_GROUP_project_metrics_file }}"
        dest: "{{ lookup('env','METRICS_BASE_PATH') | mandatory }}/{{ test_name }}/{{ _server_name }}.txt"
        flat: yes
      vars:
        _server_name: "{{ group_names[0] }}"

- name: Performs initial analysis on perf test metrics (using R on controller)
  hosts: clients
  any_errors_fatal: true
  tasks:
    - name: Plotting perf test metrics
      delegate_to: 127.0.0.1
      shell:
        cmd: |
          ./perftest_analysis.R {{ _metrics_file }} {{ _output_folder }} {{ _output_file_prefix }}
        chdir: "{{ _working_dir }}"
      vars:
        _working_dir: "{{ lookup('env','LOCAL_SCRIPTS_PATH') | mandatory }}"
        _metrics_path: "{{ lookup('env','METRICS_BASE_PATH') | mandatory }}/{{ test_name }}"
        _server_name: "{{ clients_GROUP_current_client_name }}"
        _metrics_file: "{{ _metrics_path }}/{{ _server_name }}.txt"
        _output_folder: "{{ _metrics_path }}"
        _output_file_prefix: "{{ _server_name }}_"

# ------------------------------------------------------------------------------------ Cleanup

- name: Cleans up workers
  hosts: workers

  tasks:
    - name: Deleting worker logs
      shell:
        cmd: |
          set -m
          # clean up log files (errors ignored)
          bash -ilc 'rm {{ workers_GROUP_project_log_file }} || true'
      when: delete_logs | default('true') | bool
