#------------------------------------------------------------------------------------------------------------
# Playbook to start all clients that initiate the load test.
# This playbook depends on all KV stores to be started first.
#------------------------------------------------------------------------------------------------------------

---
- name: Starts all clients
  hosts: clients
  tasks:
    - name: Starting all clients
      shell:
        cmd: |
          bash -ilc 'export JAVA_OPTS="-Dlog4j.configuration=file:{{ workers_GROUP_project_log_config_file}}" && \
                      ./bin/ycsb.sh run consensus {{ _metrics_params }} -P {{ clients_GROUP_config_file }} -P {{ cli_params }}'
        chdir: "{{ clients_GROUP_working_dir }}"
      vars:
        _metrics_params: "-p measurementtype=timeseries -p exportfile={{ workers_GROUP_project_metrics_file }} -p metricsprefix={{ graphite_prefix }} -p exporter=site.ycsb.measurements.exporter.GraphiteMeasurementsExporter"