#------------------------------------------------------------------------------------------------------------
# Stops workers optionally cleans log files
#------------------------------------------------------------------------------------------------------------

---
- name: Stops workers
  hosts: workers

  tasks:
    - name: Stopping worker processes
      shell:
        cmd: |
          set -m
          
          # kill java processes (errors ignored)
          bash -ilc 'kill $(ps -A | grep java | awk "{print $1}") || true'
