#------------------------------------------------------------------------------------------------------------
# Playbook to start all KV stores.
# This playbook depends on all the nodes to be started first.
#------------------------------------------------------------------------------------------------------------

---
- name: Starts all KV stores
  hosts: stores
  tasks:
    - name: Starting all KV stores (async)
      shell:
        cmd: |
          set -m
          
          # run in background
          bash -ilc 'java \
                      -Dlog4j.configuration=file:{{ workers_GROUP_project_log_config_file}} \
                      -cp "lib/*:*" \
                      com.mboysan.consensus.KVStoreServerCLI {{ _metrics_params }} {{ _mandatory_params }} {{ cli_params }}' &
          
          bash -ilc '{{ all_GROUP_home_dir }}/check_state.sh "store started" {{ workers_GROUP_project_log_file }}'
        chdir: "{{ nodes_GROUP_working_dir }}"
      vars:
        _metrics_params: >-
          metrics.exportfile={{ workers_GROUP_project_metrics_file }}
          metrics.separator={{ nodes_GROUP_jvm_metrics_separator }}
          metrics.step={{ nodes_GROUP_jvm_metrics_step }}
        _mandatory_params: >-
          --store port={{ stores_GROUP_client_serving_port }}
          --node node.id={{ stores_GROUP_current_node_id }} port={{ stores_GROUP_node_serving_port }} destinations={{ workers_GROUP_node_destinations }}
      async: 100
      poll: 0
      register: start_stores_task

    - name: Waiting stores to start
      async_status:
        jid: "{{ start_stores_task.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 10