#------------------------------------------------------------------------------------------------------------
# Playbook to start all clients that initiate the load test.
# This playbook depends on all KV stores to be started first.
#------------------------------------------------------------------------------------------------------------

---
- name: Starts client(s)
  hosts: clients
  tasks:
    - name: Starting client(s) (perf test)
      shell:
        cmd: |
          set -m
          
          workload="{{ workload }}"
          workloadFile="{{ clients_GROUP_workloads_dir }}/{{ workload }}"
          if [ ! -f "$workloadFile" ]; then
            echo "received custom workload:"
            echo "$workload"
            echo "$workload" > "{{ clients_GROUP_workloads_dir }}/workload_file"
          else
            cp "$workloadFile" "{{ clients_GROUP_workloads_dir }}/workload_file"
          fi
          
          bash -ilc 'export JAVA_OPTS="-Dlog4j.configuration=file:{{ workers_GROUP_project_log_config_file}}" && \
                      ./bin/ycsb.sh run consensus {{ _metrics_params }} {{ _client_params }} {{ cli_params }} -P {{ clients_GROUP_workloads_dir }}/workload_file'
        chdir: "{{ clients_GROUP_working_dir }}"
      vars:
        _metrics_params: >-
          -p measurementtype=raw
          -p measurement.raw.output_file={{ workers_GROUP_project_metrics_file }}
          -p measurement.raw.graphite=true
          -p measurement.raw.separator=,
          -p exportfile={{ workers_GROUP_project_metrics_file }}
        _client_params: >-
          -p transport.tcp.clientPoolSize=-1
          -p transport.tcp.destinations={{ workers_GROUP_store_destinations }}