#------------------------------------------------------------------------------------------------------------
# Starts workers for perf tests
#------------------------------------------------------------------------------------------------------------

---
- ansible.builtin.import_playbook: util_start_nodes.yaml
  vars:
    cli_params: "protocol={{ consensus_protocol }} {{ node_cli_params | default('') }}"

- ansible.builtin.import_playbook: util_start_stores.yaml
  vars:
    cli_params: "protocol={{ consensus_protocol }} {{ store_cli_params | default('') }}"

- ansible.builtin.import_playbook: util_start_clients.yaml
  vars:
    workload: "{{ test_workload }}"