#------------------------------------------------------------------------------------------------------------
# Analyzes the metrics collected on the processor
#------------------------------------------------------------------------------------------------------------

---

- name: Make MERGED metrics directory on processor
  hosts: processors
  any_errors_fatal: true
  tasks:
    - name: Creating MERGED metrics directory for the test
      file:
        path: '{{ processors_GROUP_project_metrics_path }}/MERGED'
        state: directory

- name: Merges and analyzes metrics
  hosts: processors
  any_errors_fatal: true
  tasks:
    - name: Merging metrics
      shell:
        cmd: |
          bash -ilc './merge_metrics.R {{ _metrics_path }} {{ _output_folder }} {{ test_names }}' > {{ all_GROUP_ansible_cmd_out }}
        chdir: "{{ all_GROUP_home_dir }}"
      vars:
        _metrics_path: "{{ processors_GROUP_project_metrics_path }}"
        _output_folder: "{{ _metrics_path }}/MERGED"

    - name: Doing performance analysis
      shell:
        cmd: |
          bash -ilc './performance_analysis.R {{ _metrics_file }} {{ _output_folder }} {{ test_names }}' > {{ all_GROUP_ansible_cmd_out }}
        chdir: "{{ all_GROUP_home_dir }}"
      vars:
        _metrics_file: "{{ processors_GROUP_project_metrics_path }}/MERGED/client.raw.merged.csv"
        _output_folder: "{{ processors_GROUP_project_metrics_path }}/MERGED"

    - name: Doing message analysis
      shell:
        cmd: |
          bash -ilc './message_analysis.R {{ _metrics_file }} {{ _output_folder }} {{ test_names }}' > {{ all_GROUP_ansible_cmd_out }}
        chdir: "{{ all_GROUP_home_dir }}"
      vars:
        _metrics_file: "{{ processors_GROUP_project_metrics_path }}/MERGED/store.raw.merged.csv"
        _output_folder: "{{ processors_GROUP_project_metrics_path }}/MERGED"

    - name: Doing resource usage analysis
      shell:
        cmd: |
          bash -ilc './resource_usage_analysis.R {{ _metrics_file }} {{ _output_folder }} {{ test_names }}' > {{ all_GROUP_ansible_cmd_out }}
        chdir: "{{ all_GROUP_home_dir }}"
      vars:
        _metrics_file: "{{ processors_GROUP_project_metrics_path }}/MERGED/store.raw.merged.csv"
        _output_folder: "{{ processors_GROUP_project_metrics_path }}/MERGED"

- name: Fetches the results to controller
  hosts: processors
  any_errors_fatal: true
  tasks:
    - name: Fetching the summary data
      synchronize:
        src: "{{ _metrics_file }}"
        dest: "{{ _destination_on_controller }}"
        mode: pull
      vars:
        _metrics_file: "{{ processors_GROUP_project_metrics_path }}/MERGED/all.summary.merged.csv"
        _destination_on_controller: "{{ lookup('env','COLLECTED_METRICS_PATH') | mandatory }}/{{ test_names }}/"

    - name: Compressing raw plot data
      shell:
        cmd: |
          tar -cvzf {{ _archive_name }} {{ _files }} > {{ all_GROUP_ansible_cmd_out }}
        chdir: "{{ processors_GROUP_project_metrics_path }}/MERGED/"
      vars:
        _files: "*.dat"
        _archive_name: "plot_raw_data.tar.gz"

    - name: Fetching raw plot data
      synchronize:
        src: "{{ _archive_file }}"
        dest: "{{ _destination_on_controller }}"
        mode: pull
      vars:
        _archive_file: "{{ processors_GROUP_project_metrics_path }}/MERGED/plot_raw_data.tar.gz"
        _destination_on_controller: "{{ lookup('env','COLLECTED_METRICS_PATH') | mandatory }}/{{ test_names }}/"

    - name: Extracting raw plot data on controller
      delegate_to: 127.0.0.1
      shell:
        cmd: |
          tar -xvzf {{ _archive_name }}
        chdir: "{{ lookup('env','COLLECTED_METRICS_PATH') | mandatory }}/{{ test_names }}/"
      vars:
        _archive_name: "plot_raw_data.tar.gz"
