#------------------------------------------------------------------------------------------------------------
# Analyzes the metrics collected on the processor
#------------------------------------------------------------------------------------------------------------

---

- name: Merges and analyzes metrics
  hosts: processors
  any_errors_fatal: true
  tasks:
    - name: Merging metrics
      shell:
        cmd: |
          bash -ilc './merge_metrics.R {{ _args }}' > {{ all_GROUP_ansible_cmd_out }}
        chdir: "{{ all_GROUP_home_dir }}"
      vars:
        _io_folder: "{{ processors_GROUP_project_metrics_path }}/{{ test_group }}"
        _merge_client_metrics: "merge_client_metrics={{ analyze_client_metrics | default(true)}}"
        _merge_store_metrics: "merge_store_metrics={{ analyze_store_message_metrics or analyze_store_jvm_metrics }}"
        _args: "{{ _io_folder }} {{ _merge_client_metrics }} {{ _merge_store_metrics }}"

    - name: Doing performance analysis
      shell:
        cmd: |
          bash -ilc './analyze_client_metrics.R {{ _args }}' > {{ all_GROUP_ansible_cmd_out }}
        chdir: "{{ all_GROUP_home_dir }}"
      vars:
        _io_folder: "{{ processors_GROUP_project_metrics_path }}/{{ test_group }}"
        _input_file: "client.raw.merged.csv"
        _remove_outliers_per_test: "remove_outliers_per_test={{ remove_outliers_per_test | default(true) }}"
        _timescale_in_milliseconds: "timescale_in_milliseconds={{ timescale_in_milliseconds | default(false) }}"
        _args: "{{ _io_folder }} {{ _input_file }} {{ _remove_outliers_per_test }} {{ _timescale_in_milliseconds }}"
      when: analyze_client_metrics | default(true)

    - name: Doing message analysis
      shell:
        cmd: |
          bash -ilc './analyze_store_message_metrics.R {{ _args }}' > {{ all_GROUP_ansible_cmd_out }}
        chdir: "{{ all_GROUP_home_dir }}"
      vars:
        _io_folder: "{{ processors_GROUP_project_metrics_path }}/{{ test_group }}"
        _input_file: "store.message.raw.merged.csv"
        _args: "{{ _io_folder }} {{ _input_file }}"
      when: analyze_store_message_metrics

    - name: Doing memory usage analysis
      shell:
        cmd: |
          bash -ilc './analyze_store_memory_metrics.R {{ _args }}' > {{ all_GROUP_ansible_cmd_out }}
        chdir: "{{ all_GROUP_home_dir }}"
      vars:
        _io_folder: "{{ processors_GROUP_project_metrics_path }}/{{ test_group }}"
        _input_file: "store.memory.raw.merged.csv"
        _args: "{{ _io_folder }} {{ _input_file }}"
      when: analyze_store_jvm_metrics

    - name: Doing cpu usage analysis
      shell:
        cmd: |
          bash -ilc './analyze_store_cpu_metrics.R {{ _args }}' > {{ all_GROUP_ansible_cmd_out }}
        chdir: "{{ all_GROUP_home_dir }}"
      vars:
        _io_folder: "{{ processors_GROUP_project_metrics_path }}/{{ test_group }}"
        _input_file: "store.cpu.raw.merged.csv"
        _args: "{{ _io_folder }} {{ _input_file }}"
      when: analyze_store_jvm_metrics

- name: Fetches the results to controller
  hosts: processors
  any_errors_fatal: true
  tasks:
    - name: Creating sync directory for metrics data to be fetched
      file:
        path: '{{ processors_GROUP_project_metrics_path }}/{{ test_group }}/sync'
        state: directory

    - name: Moving summary results to sync directory
      shell:
        cmd: |
          mv *.summary.merged.csv sync/
        chdir: "{{ processors_GROUP_project_metrics_path }}/{{ test_group }}/"

    - name: Moving the generated plot images to sync directory
      shell:
        cmd: |
          mv *.out.* sync/
        chdir: "{{ processors_GROUP_project_metrics_path }}/{{ test_group }}/"
      when: collect_plots | default(true)

    - name: Moving CLIENT raw data to sync directory
      shell:
        cmd: |
          mv client.raw.merged.csv sync/
        chdir: "{{ processors_GROUP_project_metrics_path }}/{{ test_group }}/"
      when: collect_client_raw_data | default(false)

    - name: Moving STORE raw data to sync directory
      shell:
        cmd: |
          mv store.*.raw.merged.csv sync/
        chdir: "{{ processors_GROUP_project_metrics_path }}/{{ test_group }}/"
      when: collect_store_raw_data | default(false)

    - name: Compressing metrics data and deleting sync directory
      shell:
        cmd: |
          tar -cvzf {{ _archive_name }} {{ _folder }} > {{ all_GROUP_ansible_cmd_out }}
          rm -r {{ _folder }} >> {{ all_GROUP_ansible_cmd_out }}
        chdir: "{{ processors_GROUP_project_metrics_path }}/{{ test_group }}/"
      vars:
        _folder: "sync/"
        _archive_name: "sync.tar.gz"

    - name: Fetching metrics data
      synchronize:
        src: "{{ _archive_file }}"
        dest: "{{ _destination_on_controller }}"
        mode: pull
      vars:
        _archive_file: "{{ processors_GROUP_project_metrics_path }}/{{ test_group }}/sync.tar.gz"
        _destination_on_controller: "{{ lookup('env','COLLECTED_METRICS_PATH') | mandatory }}/{{ test_group }}/"

    - name: Extracting metrics data on controller
      delegate_to: 127.0.0.1
      shell:
        cmd: |
          tar -xvzf {{ _archive_name }} --strip-components=1
        chdir: "{{ lookup('env','COLLECTED_METRICS_PATH') | mandatory }}/{{ test_group }}/"
      vars:
        _archive_name: "sync.tar.gz"
