#------------------------------------------------------------------------------------------------------------
# Cleanup resources
#------------------------------------------------------------------------------------------------------------

---

- name: Cleans up processors
  hosts: processors
  tasks:
    - name: Deleting collected metrics
      shell:
        cmd: |
          set -m
          # clean up metrics files (errors ignored)
          bash -ilc 'rm -r {{ processors_GROUP_project_metrics_path }} || true'
      when: cleanup_processor | default('true') | bool