#------------------------------------------------------------------------------------------------------------
# Collects metrics generated at workers and sends them to processors
#------------------------------------------------------------------------------------------------------------

---

- name: Configure R installation
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Configuring R installation (async)
      shell:
        cmd: |
          bash -ilc './util.R' > {{ all_GROUP_ansible_cmd_out }}
        chdir: "{{ all_GROUP_home_dir }}"
      async: 600
      poll: 0
      register: setup_r

    - name: Waiting all to finish R setup
      async_status:
        jid: "{{ setup_r.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 10
      delay: 60

- name: Collects client metrics into csv files
  hosts: clients
  any_errors_fatal: true
  tasks:
    - name: Grouping client (perf test) metrics
      shell:
        cmd: |
          bash -ilc './collect_client_metrics.R {{ _metrics_file }} {{ _output_folder }} {{ test_name }} {{ consensus_protocol }}' > {{ all_GROUP_ansible_cmd_out }}
        chdir: "{{ _working_dir }}"
      vars:
        _working_dir: "{{ all_GROUP_home_dir }}"
        _metrics_path: "{{ workers_GROUP_project_metrics_path }}"
        _metrics_file: "{{ workers_GROUP_project_metrics_file }}"
        _output_folder: "{{ _metrics_path }}"

- name: Collects store metrics into csv files
  hosts: stores
  any_errors_fatal: true
  tasks:
    - name: Grouping store metrics
      shell:
        cmd: |
          bash -ilc './collect_store_metrics.R {{ _metrics_file }} {{ _output_folder }} {{ test_name }} {{ consensus_protocol }}' > {{ all_GROUP_ansible_cmd_out }}
        chdir: "{{ _working_dir }}"
      vars:
        _working_dir: "{{ all_GROUP_home_dir }}"
        _metrics_path: "{{ workers_GROUP_project_metrics_path }}"
        _metrics_file: "{{ workers_GROUP_project_metrics_file }}"
        _output_folder: "{{ _metrics_path }}"


# TODO: file transfer using nc
# https://superuser.com/questions/98089/sending-file-via-netcat
