#------------------------------------------------------------------------------------------------------------
# Playbook to inject network faults in the system.
# This playbook depends on all KV stores to be started first.
#------------------------------------------------------------------------------------------------------------

---
- name: Fault injection
  hosts: nodes
  tasks:
    - name: Prepare inject_fault script
      template:
        src: inject_fault_consensus.template.sh
        dest: "{{ _home_dir }}/inject_fault_consensus.sh"
        mode: "+x"
      vars:
        _mandatory_params: "destinations={{ workers_GROUP_store_destinations }} transport.message.callbackTimeoutMs=60000"
        _server_name: "{{ inventory_hostname }}"
        _home_dir: "{{ all_GROUP_home_dir }}"
        _condition: "{{ condition }}"

    - name: Running inject_fault script
      shell:
        cmd: |
          bash -ilc './inject_fault_consensus.sh'
        chdir: "{{ all_GROUP_home_dir }}"
      async: "{{ duration_sec * 2 | default(500) }}"
      poll: 0
      register: inject_fault_task