#------------------------------------------------------------------------------------------------------------
# Collects metrics generated at workers to a local text file.
#------------------------------------------------------------------------------------------------------------

---
- name: Sends metrics from workers to collector
  hosts: workers
  tasks:
    - name: Sending graphite metrics
      shell:
        cmd: |
          # Sends metrics with netcat like the following: $> nc -N [host] [port] < [metrics-file]
          bash -ilc 'nc -N {{ workers_GROUP_collector_private_ip }} {{ workers_GROUP_graphite_nc_port }} < {{ workers_GROUP_project_metrics_file }}'
