#------------------------------------------------------------------------------------------------------------
# Playbook to configure some runtime parameters.
#------------------------------------------------------------------------------------------------------------

---
- name: Runtime configuration
  hosts: workers
  tasks:
    - name: Configuring log4j
      template:
        src: log4j.template.properties
        dest: '{{ workers_GROUP_project_log_config_file }}'
