#------------------------------------------------------------------------------------------------------------
# Merges and plots metrics from several tests.

# Run it:
# ansible-playbook -vvv playbooks/W1_merge_and_plot_metrics.yaml -e "tests_to_merge='S1 S2'"
#------------------------------------------------------------------------------------------------------------

---

- name: Merge and plot metrics
  hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: Merging metrics (using R on controller)
      delegate_to: 127.0.0.1
      shell:
        cmd: |
          ./merge_metrics.R {{ _input_folder }} {{ _output_folder }} {{ tests_to_merge }}
        chdir: "{{ _working_dir }}"
      vars:
        _working_dir: "{{ lookup('env','LOCAL_SCRIPTS_PATH') | mandatory }}"
        _input_folder: "{{ lookup('env','METRICS_BASE_PATH') | mandatory }}"
        _output_folder: "{{ _input_folder }}/MERGED"
