#------------------------------------------------------------------------------------------------------------
# Runs the tests and analyzes metrics from the tests run.
#------------------------------------------------------------------------------------------------------------

---
- hosts: all, localhost
  tasks:
    - name: Setting global variables
      set_fact:
        test_group: "W7"
        workload_definition: "workload_rw_10k"
        analyze_client_metrics: true
        analyze_store_jvm_metrics: true
        analyze_store_message_metrics: true

#---------------------------------------------------------------

# raft consensus test
- import_playbook: T_load_test_consensus_raft.yaml
  vars:
    test_name: "T1"

# bizur consensus test with 1k buckets
- import_playbook: T_load_test_consensus_bizur.yaml
  vars:
    test_name: "T2"
    override_node_cli_params: >-
      --node
      bizur.numBuckets=1000

# bizur consensus test with infinite buckets
- import_playbook: T_load_test_consensus_bizur.yaml
  vars:
    test_name: "T3"

#---------------------------------------------------------------

- import_playbook: util_analyze_metrics.yaml
  vars:
    collect_client_raw_data: true
    collect_store_raw_data: true

- import_playbook: util_cleanup_processors.yaml
