#------------------------------------------------------------------------------------------------------------
# Runs the tests and analyzes metrics from the tests run.
#------------------------------------------------------------------------------------------------------------

---
- hosts: all, localhost
  tasks:
    - name: Setting global variables
      set_fact:
        test_group: "W8"
        workload_definition: "workload_rw_10k"
        analyze_client_metrics: true
        analyze_store_jvm_metrics: false
        analyze_store_message_metrics: false

        inject_fault:
          condition: 'disconnect follower' # only applicable to consensus-raft
          delay_sec: 20
          duration_sec: 30

#---------------------------------------------------------------

# raft consensus test
- import_playbook: T_load_test_consensus_raft.yaml
  vars:
    test_name: "T1"

# bizur consensus test with unbounded number of buckets
- import_playbook: T_load_test_consensus_bizur.yaml
  vars:
    test_name: "T2"

# raft consensus on etcd test
- import_playbook: T_load_test_etcd_raft.yaml
  vars:
    test_name: "T3"

# raft consensus on consul test
- import_playbook: T_load_test_consul_raft.yaml
  vars:
    test_name: "T4"

#---------------------------------------------------------------

- import_playbook: util_analyze_metrics.yaml
  vars:
    collect_client_raw_data: true
    collect_store_raw_data: true

- import_playbook: util_cleanup_processors.yaml
