services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./config/scripts/influx_create_buckets.sh:/docker-entrypoint-initdb.d/influx_create_buckets.sh
      - ./config/scripts:/home/influxdb
      - ./metrics:/var/log
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=mboysan_org
      - DOCKER_INFLUXDB_INIT_BUCKET=init_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./logs:/var/log
      - ./config/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafana-renderer
    ports:
      - "8081"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-image-renderer
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    configs:
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/datasources.yaml
    volumes:
      - ./config/grafana-dashboard-provision.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./config/grafana_dashboards:/var/lib/grafana/dashboards:rw
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
      - renderer

configs:
  grafana_datasources:
    file: ./config/grafana-datasources.yaml

volumes:
  influxdb_data:
  grafana_data: