# name of the current node (e.g. node0) taken from the 'nodes' hosts
nodes_current_node_name: "{{ group_names[0] }}"
# id of the current node (e.g. 0) taken from the 'nodes' hosts
nodes_current_node_id: "{{ group_names[0] | regex_search('[0-9]')}}"

# cli parameters for the java executable
#nodes_cli_params:
nodes_node_serving_port: "{{ lookup('env','NODE_SERVING_PORT') | mandatory }}"