all_GROUP_aws_region: "{{ lookup('env','AWS_DEFAULT_REGION') | mandatory }}"

all_GROUP_current_server_name: "{{ inventory_hostname }}"

# home directory of all instances
all_GROUP_home_dir: /home/ubuntu