# working directory of the nodes
nodes_GROUP_working_dir: '{{ workers_GROUP_project_dir }}/consensus'

# name of the current node (e.g. node0) taken from the 'nodes' hosts
nodes_GROUP_current_node_name: "{{ group_names[0] }}"
# id of the current node (e.g. 0) taken from the 'nodes' hosts
nodes_GROUP_current_node_id: "{{ group_names[0] | regex_search('[0-9]')}}"

# tcp port used to serve nodes
nodes_GROUP_node_serving_port: "{{ lookup('env','NODE_SERVING_PORT') | mandatory }}"