# working directory of the nodes
nodes_GROUP_working_dir: '{{ workers_GROUP_project_dir }}/consensus'

# working directory of etcd nodes
nodes_GROUP_etcd_working_dir: '{{ all_GROUP_home_dir }}/etcd'

# working directory of consul nodes
nodes_GROUP_consul_working_dir: '{{ all_GROUP_home_dir }}/consul'

# config directory of consul nodes
nodes_GROUP_consul_config_dir: '{{ nodes_GROUP_consul_working_dir }}/config'

# id of the current node (e.g. 0) taken from the 'nodes' hosts
nodes_GROUP_current_node_id: "{{ inventory_hostname | regex_search('[0-9]')}}"

# tcp port used to serve nodes
nodes_GROUP_node_serving_port: "{{ lookup('env','NODE_SERVING_PORT') | mandatory }}"
# tcp port used to serve clients (only used by etcd)
nodes_GROUP_client_serving_port: "{{ lookup('env','CLIENT_SERVING_PORT') | mandatory }}"

# config for metrics
# configure metrics separator
nodes_GROUP_jvm_metrics_separator: ','
# configure interval for jvm metrics collection (in milliseconds)
nodes_GROUP_jvm_metrics_step: '2000'