# name of the current node (e.g. node0) taken from the 'stores' hosts
stores_GROUP_current_node_name: "{{ inventory_hostname }}"
# id of the current node (e.g. 0) taken from the 'stores' hosts
stores_GROUP_current_node_id: "{{ inventory_hostname | regex_search('[0-9]')}}"

# tcp port used to serve nodes
stores_GROUP_node_serving_port: "{{ nodes_GROUP_node_serving_port }}"
# tcp port used to serve clients
stores_GROUP_client_serving_port: "{{ lookup('env','CLIENT_SERVING_PORT') | mandatory }}"
